[package]
name = "test-parachain-adder"
version = "0.8.28"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test parachain which adds to a number as its state transition"
edition = "2018"
build = "build.rs"

[dependencies]
parachain = { version = "0.8.28", package = "tetcoin-parachain", path = "../../", default-features = false, features = [ "wasm-api" ] }
tetsy-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
tetcore-std = { version = "2.0.2", default-features = false }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
dlmalloc = { version = "0.2.1", features = [ "global" ] }

# We need to make sure the global allocator is disabled until we have support of full tetcore externalities
tet-io = { git = "https://github.com/tetcoin/tetcore", branch = "master", default-features = false, features = [ "disable_allocator" ] }

[build-dependencies]
wasm-builder = "3.0.0"

[features]
default = [ "std" ]
std = [
	"parachain/std",
	"tetcore-std/std",
]
