[package]
name = "tetcoin-network-bridge"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
async-trait = "0.1.42"
futures = "0.3.12"
tracing = "0.1.22"
tracing-futures = "0.2.4"
tetcoin-primitives = { version = "0.8.28", path = "../../../primitives" }
tetsy-scale-codec = { version = "2.0.1", default-features = false, features = ["derive"] }
tc-authority-discovery = { version = "0.8.0" }
tc-network = { version = "0.8.0" }
tetcoin-subsystem = { package = "tetcoin-node-subsystem", path = "../../subsystem" }
tetcoin-node-network-protocol = { path = "../protocol" }

[dev-dependencies]
assert_matches = "1.4.0"
parking_lot = "0.11.1"
tetcoin-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
tetcoin-node-subsystem-util = { path = "../../subsystem-util"}
tet-core = "2.0.2"
tp-keyring = { version = "2.0.2" }
