[package]
name = "tetcoin-availability-distribution"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.22"
tracing-futures = "0.2.4"
tetsy-scale-codec = { version = "2.0.0", features = ["std"]  }
tetcoin-primitives = { version = "0.8.28", path = "../../../primitives" }
tetcoin-erasure-coding = { version = "0.8.28", path = "../../../erasure-coding" }
tetcoin-subsystem = { package = "tetcoin-node-subsystem", path = "../../subsystem" }
tetcoin-node-network-protocol = { path = "../../network/protocol" }
tetcoin-node-subsystem-util = { path = "../../subsystem-util" }
tet-core = { version = "2.0.2", features = ["std"]  }
tp-keystore = { version = "0.8.1" }
thiserror = "1.0.23"

[dev-dependencies]
tetcoin-subsystem-testhelpers = { package = "tetcoin-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
tet-core = { version = "2.0.2", features = ["std"] }
tet-application-crypto = { version = "2.0.2" }
tp-keyring = { version = "2.0.2" }
tetcore-tracing = { version = "2.0.2" }
tc-keystore = { version = "2.0.0" }
assert_matches = "1.4.0"
maplit = "1.0"
