[package]
name = "tetcoin-availability-distribution"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.22"
tracing-futures = "0.2.4"
tetsy-scale-codec = { version = "2.0.0", features = ["std"]  }
tetcoin-primitives = { path = "../../../primitives" }
tetcoin-erasure-coding = { path = "../../../erasure-coding" }
tetcoin-subsystem = { package = "tetcoin-node-subsystem", path = "../../subsystem" }
tetcoin-node-network-protocol = { path = "../../network/protocol" }
tetcoin-node-subsystem-util = { path = "../../subsystem-util" }
tet-core = { git = "https://github.com/tetcoin/tetcore", branch = "master", features = ["std"]  }
tp-keystore = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
thiserror = "1.0.23"

[dev-dependencies]
tetcoin-subsystem-testhelpers = { package = "tetcoin-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
tet-core = { git = "https://github.com/tetcoin/tetcore", branch = "master", features = ["std"] }
tet-application-crypto = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
tp-keyring = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
tetcore-tracing = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
tc-keystore = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
assert_matches = "1.4.0"
maplit = "1.0"
