[package]
name = "test-parachain-halt"
version = "0.8.28"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Test parachain which executes forever"
edition = "2018"
build = "build.rs"

[dependencies]

[build-dependencies]
wasm-builder = "3.0.1"

[features]
default = [ "std" ]
std = []
