version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels: ["A2-insubstantial", "B0-silent", "C1-low"]
    # Handle updates for crates from github.com/tetcoin/tetcore manually.
    ignore:
      - dependency-name: "tetcore-*"
      - dependency-name: "tc-*"
      - dependency-name: "tp-*"
      - dependency-name: "fabric-*"
      - dependency-name: "fork-tree"
      - dependency-name: "noble-*"
    schedule:
      interval: "daily"
