[package]
name = "tetcoin-statement-distribution"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Statement Distribution Subsystem"
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.22"
tracing-futures = "0.2.4"
tetcoin-primitives = { path = "../../../primitives" }
node-primitives = { package = "tetcoin-node-primitives", path = "../../primitives" }
tp-staking = { git = "https://github.com/tetcoin/tetcore", branch = "master", default-features = false }
tetcoin-subsystem = { package = "tetcoin-node-subsystem", path = "../../subsystem" }
tetcoin-node-subsystem-util = { path = "../../subsystem-util" }
tetcoin-node-network-protocol = { path = "../../network/protocol" }
arrayvec = "0.5.2"
indexmap = "1.6.1"

[dev-dependencies]
tetcoin-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
assert_matches = "1.4.0"
tp-keyring = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
tet-core = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
tp-application-crypto = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
tp-keystore = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
tc-keystore = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
