// Copyright 2017-2020 Parity Technologies (UK) Ltd.
// This file is part of Tetcoin.

// Tetcoin is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Tetcoin is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Tetcoin.  If not, see <http://www.gnu.org/licenses/>.
//! Autogenerated weights for noble_utility
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 2.0.0
//! DATE: 2020-12-09, STEPS: [50, ], REPEAT: 20, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("kusama-dev"), DB CACHE: 128

// Executed Command:
// target/release/tetcoin
// benchmark
// --chain=kusama-dev
// --steps=50
// --repeat=20
// --noble=noble_utility
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --header=./file_header.txt
// --output=./runtime/kusama/src/weights/


#![allow(unused_parens)]
#![allow(unused_imports)]

use fabric_support::{traits::Get, weights::Weight};
use tetcore_std::marker::PhantomData;

/// Weight functions for noble_utility.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: fabric_system::Config> noble_utility::WeightInfo for WeightInfo<T> {
	fn batch(c: u32, ) -> Weight {
		(19_612_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_988_000 as Weight).saturating_mul(c as Weight))
	}
	fn as_derivative() -> Weight {
		(5_849_000 as Weight)
	}
	fn batch_all(c: u32, ) -> Weight {
		(21_934_000 as Weight)
			// Standard Error: 0
			.saturating_add((1_503_000 as Weight).saturating_mul(c as Weight))
	}
}
