[package]
name = "tetcoin-approval-distribution"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
tetcoin-node-primitives = { version = "0.1.0", path = "../../primitives" }
tetcoin-node-network-protocol = { path = "../protocol" }
tetcoin-node-subsystem = { path = "../../subsystem" }
tetcoin-node-subsystem-util = { path = "../../subsystem-util" }
tetcoin-primitives = { version = "0.8.28", path = "../../../primitives" }

futures = "0.3.8"
tracing = "0.1.22"
# tracing-futures = "0.2.4"

[dev-dependencies]
tet-core = { version = "2.0.2", features = ["std"] }

tetcoin-node-subsystem-util = { path = "../../subsystem-util" }
tetcoin-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }

assert_matches = "1.4.0"
schnorrkel = { version = "0.9.1", default-features = false }
rand_core = "0.6.3" # should match schnorrkel
env_logger = "0.8.2"
log = "0.4.13"
