[package]
name = "tetcoin-collator-protocol"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.22"
tracing-futures = "0.2.4"
thiserror = "1.0.23"


tetcoin-primitives = { path = "../../../primitives" }
tetcoin-node-network-protocol = { path = "../../network/protocol" }
tetcoin-node-subsystem-util = { path = "../../subsystem-util" }
tetcoin-subsystem = { package = "tetcoin-node-subsystem", path = "../../subsystem" }

[dev-dependencies]
log = "0.4.13"
env_logger = "0.8.2"
assert_matches = "1.4.0"
futures-timer = "3.0.2"

tet-core = { git = "https://github.com/tetcoin/tetcore", branch = "master", features = ["std"] }
tp-keyring = { git = "https://github.com/tetcoin/tetcore", branch = "master" }

tetcoin-subsystem-testhelpers = { package = "tetcoin-node-subsystem-test-helpers", path = "../../subsystem-test-helpers" }
