# set tag manually --set image.tag=latest
image:
  repository: parity/tetcoin
  tag: latest
  pullPolicy: Always
  basepath: /tetcoin
  executable: /usr/local/bin/tetcoin


# if set to true a service account for tetcoin will be created
rbac:
  enable: true
  name: tetcoin

# name of the statefulset
app: tetcoin
node_group: tetcoin
listen_node_port: true

nodes:
  replicas: 2
  args:
    - --chain
    - alexander
    # serve rpc within the local network
    # - fenced off the world via firewall
    # - used for health checks
    - --rpc-external
    - --ws-external
    # - --log
    # - sub-libp2p=trace


validator: {}
# providing 'keys' string via --set commandline parameter will run the nodes
# in validator mode (--validator).

# maybe adopt resource limits here to the nodes of the pool
# resources:
#   memory: "5Gi"
#   cpu: "1.5"

