[package]
name = "tetcoin-pov-distribution"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
thiserror = "1.0.23"
tracing = "0.1.22"
tracing-futures = "0.2.4"

tetcoin-primitives = { path = "../../../primitives" }
tetcoin-subsystem = { package = "tetcoin-node-subsystem", path = "../../subsystem" }
tetcoin-node-subsystem-util = { path = "../../subsystem-util" }
tetcoin-node-network-protocol = { path = "../../network/protocol" }

[dev-dependencies]
assert_matches = "1.4.0"
env_logger = "0.8.1"
log = "0.4.13"

tet-core = "2.0.2"
tp-keyring = { git = "https://github.com/tetcoin/tetcore", branch = "master" }

tetcoin-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
