[package]
name = "test-parachain-adder-collator"
version = "0.7.26"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Collator for the adder test parachain"
edition = "2018"

[[bin]]
name = "adder-collator"
path = "src/main.rs"

[dependencies]
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
futures = "0.3.12"
futures-timer = "3.0.2"
log = "0.4.13"
structopt = "0.3.21"

test-parachain-adder = { path = ".." }
tetcoin-primitives = { path = "../../../../primitives" }
tetcoin-cli = { path = "../../../../cli" }
tetcoin-service = { path = "../../../../node/service" }
tetcoin-node-primitives = { path = "../../../../node/primitives" }
tetcoin-node-subsystem = { path = "../../../../node/subsystem" }

tc-cli = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
tet-core = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
tc-authority-discovery = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
tc-service = { git = "https://github.com/tetcoin/tetcore", branch = "master" }

[dev-dependencies]
tetcoin-parachain = { path = "../../.." }
tetcoin-test-service = { path = "../../../../node/test/service" }

tetcore-test-utils = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
tc-service = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
tp-keyring = { git = "https://github.com/tetcoin/tetcore", branch = "master" }

tokio = { version = "0.2", features = ["macros"] }

[features]
real-overseer = [ "tetcoin-service/real-overseer" ]
