[package]
name = "tetcoin-node-core-runtime-api"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.22"
tracing-futures = "0.2.4"
memory-lru = "0.1.0"
tetsy-util-mem = { version = "0.9.0", default-features = false }

tp-api = { version = "2.0.2" }
tet-core = "2.0.2"

tetcoin-primitives = { version = "0.8.28", path = "../../../primitives" }
tetcoin-subsystem = { package = "tetcoin-node-subsystem", path = "../../subsystem" }
tetcoin-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
tet-core = "2.0.2"
futures = { version = "0.3.12", features = ["thread-pool"] }
tetcoin-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
