[package]
name = "tetcoin-node-core-chain-api"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.22"
tracing-futures = "0.2.4"
tp-blockchain = { git = "https://github.com/tetcoin/tetcore", branch = "master" }
tetcoin-primitives = { path = "../../../primitives" }
tetcoin-subsystem = { package = "tetcoin-node-subsystem", path = "../../subsystem" }
tetcoin-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
futures = { version = "0.3.12", features = ["thread-pool"] }
maplit = "1.0.2"
tetcoin-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
tet-core = "2.0.2"
