// Copyright 2017-2020 Parity Technologies (UK) Ltd.
// This file is part of Tetcoin.

// Tetcoin is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Tetcoin is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Tetcoin.  If not, see <http://www.gnu.org/licenses/>.
//! Autogenerated weights for noble_im_online
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 2.0.0
//! DATE: 2020-12-09, STEPS: [50, ], REPEAT: 20, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("tetcoin-dev"), DB CACHE: 128

// Executed Command:
// target/release/tetcoin
// benchmark
// --chain=tetcoin-dev
// --steps=50
// --repeat=20
// --pallet=noble_im_online
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --header=./file_header.txt
// --output=./runtime/tetcoin/src/weights/


#![allow(unused_parens)]
#![allow(unused_imports)]

use fabric_support::{traits::Get, weights::Weight};
use tetcore_std::marker::PhantomData;

/// Weight functions for noble_im_online.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: fabric_system::Config> noble_im_online::WeightInfo for WeightInfo<T> {
	fn validate_unsigned_and_then_heartbeat(k: u32, e: u32, ) -> Weight {
		(111_740_000 as Weight)
			// Standard Error: 0
			.saturating_add((217_000 as Weight).saturating_mul(k as Weight))
			// Standard Error: 1_000
			.saturating_add((510_000 as Weight).saturating_mul(e as Weight))
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}
